// Seed rows modeled on the collected team survey (mirrors the frontend sample).
export const sampleSeeds = [
  {
    rowId: '4',
    employeeId: '93345100',
    name: 'Harshavardhan',
    email: 'KKL93345100@example.com',
    onProject: true,
    projectName: 'eAction Program, Research-based project',
    expertiseRaw: 'CAD tools like 3D Experience, CATIA V5 and simulation tools like ANSYS',
    remarks: 'It would be nice if I worked with projects having the above-mentioned tools',
    submittedAt: '8/31/2026 12:35',
  },
  {
    rowId: '5',
    employeeId: '93345101',
    name: 'Priya Nair',
    email: 'KKL93345101@example.com',
    onProject: false,
    expertiseRaw: 'CATIA V6, PLM, 3D Experience, Teamcenter',
    remarks: 'Open to new PLM implementation projects.',
    submittedAt: '8/31/2026 10:12',
  },
  {
    rowId: '6',
    employeeId: '93345102',
    name: 'Rahul Deshmukh',
    email: 'KKL93345102@example.com',
    onProject: true,
    projectName: 'BIW structural analysis for EV platform',
    expertiseRaw: 'ANSYS, HyperMesh, Nastran, Abaqus, Simulation',
    remarks: 'Strong in crash and NVH simulation.',
    submittedAt: '8/30/2026 16:45',
  },
  {
    rowId: '7',
    employeeId: '93345103',
    name: 'Sneha Kulkarni',
    email: 'KKL93345103@example.com',
    onProject: false,
    expertiseRaw: 'Python, SQL, Power BI, MATLAB',
    remarks: 'Interested in data analytics and automation work.',
    submittedAt: '8/30/2026 09:30',
  },
  {
    rowId: '8',
    employeeId: '93345104',
    name: 'Arjun Menon',
    email: 'KKL93345104@example.com',
    onProject: true,
    projectName: 'Digital twin dashboard for manufacturing line',
    expertiseRaw: 'React, JavaScript, Python, SQL',
    remarks: 'Full-stack developer, likes UI-heavy projects.',
    submittedAt: '8/29/2026 14:05',
  },
  {
    rowId: '9',
    employeeId: '93345105',
    name: 'Meera Iyer',
    email: 'KKL93345105@example.com',
    onProject: false,
    expertiseRaw: 'Siemens NX, Creo, AutoCAD, CAD',
    remarks: 'Detailing and design expert, available immediately.',
    submittedAt: '8/29/2026 11:20',
  },
  {
    rowId: '10',
    employeeId: '93345106',
    name: 'Vikram Singh',
    email: 'KKL93345106@example.com',
    onProject: true,
    projectName: 'Powertrain thermal management study',
    expertiseRaw: 'ANSYS, Simulation, CAE, MATLAB, Simulink',
    remarks: 'CFD and thermal focus.',
    submittedAt: '8/28/2026 17:50',
  },
  {
    rowId: '11',
    employeeId: '93345107',
    name: 'Ananya Rao',
    email: 'KKL93345107@example.com',
    onProject: false,
    expertiseRaw: 'CATIA V5, 3D Experience, PLM',
    remarks: 'Keen to move into a research-based project.',
    submittedAt: '8/28/2026 08:15',
  },
  {
    rowId: '12',
    employeeId: '93345108',
    name: 'Karthik Reddy',
    email: 'KKL93345108@example.com',
    onProject: true,
    projectName: 'Legacy CAD migration to 3D Experience',
    expertiseRaw: 'CATIA V5, CATIA V6, 3D Experience, PLM, Java',
    remarks: 'Comfortable mentoring new joiners.',
    submittedAt: '8/27/2026 13:40',
  },
  {
    rowId: '13',
    employeeId: '93345109',
    name: 'Fatima Shaikh',
    email: 'KKL93345109@example.com',
    onProject: false,
    expertiseRaw: 'Python, C++, MATLAB, Simulink',
    remarks: 'Controls and embedded background.',
    submittedAt: '8/27/2026 09:55',
  },
]
